<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_One WayRound TripFromPopular CitiesMumb_3557dc</name>
   <tag></tag>
   <elementGuidId>eb55ee85-5487-4ab1-9fcb-0d8905b91ded</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._3-tSyS._36bm8T</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>126f9f2a-1b37-4d75-8cd8-c9b228553152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_3-tSyS _36bm8T</value>
      <webElementGuid>93873565-69f4-41dd-8717-104820c615f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tkid</name>
      <type>Main</type>
      <value>876b3309-e0d6-435b-a66e-a652aecab39f</value>
      <webElementGuid>d4616856-dadb-4b36-94df-8bb072613516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>One WayRound TripFromPopular CitiesMumbai, INBOMHyderabad, INHYDBangkok, THBKKKuala Lumpur, MYKULKolkata, INCCUBengaluru, INBLRSingapore, SGSINNew Delhi, INDELChennai, INMAADubai, AEDXBToPopular CitiesMumbai, INBOMHyderabad, INHYDBangkok, THBKKKuala Lumpur, MYKULKolkata, INCCUBengaluru, INBLRSingapore, SGSINNew Delhi, INDELChennai, INMAADubai, AEDXBAny worldwide city or airport Depart OnReturn OnAdd return date for great deals✕ Travellers | ClassSEARCH</value>
      <webElementGuid>d2e09bf0-6cd8-4b44-9ad8-ef317b7964bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_2I_P4n _6t1WkM _3HqJxg&quot;]/div[@class=&quot;_1AtVbE col-12-12&quot;]/div[@class=&quot;_3-tSyS _36bm8T&quot;]</value>
      <webElementGuid>77220a78-7b72-4188-8cff-447ff678ad64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[2]/div/div</value>
      <webElementGuid>ea07c0b4-315a-4f29-a9f4-4da9d03fe709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::div[9]</value>
      <webElementGuid>6b1e05ad-ce69-4a88-8889-0b71a0c08865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>6b258b91-577b-4501-9df0-70d56b7f90b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'One WayRound TripFromPopular CitiesMumbai, INBOMHyderabad, INHYDBangkok, THBKKKuala Lumpur, MYKULKolkata, INCCUBengaluru, INBLRSingapore, SGSINNew Delhi, INDELChennai, INMAADubai, AEDXBToPopular CitiesMumbai, INBOMHyderabad, INHYDBangkok, THBKKKuala Lumpur, MYKULKolkata, INCCUBengaluru, INBLRSingapore, SGSINNew Delhi, INDELChennai, INMAADubai, AEDXBAny worldwide city or airport Depart OnReturn OnAdd return date for great deals✕ Travellers | ClassSEARCH' or . = 'One WayRound TripFromPopular CitiesMumbai, INBOMHyderabad, INHYDBangkok, THBKKKuala Lumpur, MYKULKolkata, INCCUBengaluru, INBLRSingapore, SGSINNew Delhi, INDELChennai, INMAADubai, AEDXBToPopular CitiesMumbai, INBOMHyderabad, INHYDBangkok, THBKKKuala Lumpur, MYKULKolkata, INCCUBengaluru, INBLRSingapore, SGSINNew Delhi, INDELChennai, INMAADubai, AEDXBAny worldwide city or airport Depart OnReturn OnAdd return date for great deals✕ Travellers | ClassSEARCH')]</value>
      <webElementGuid>1b3e0607-0fd6-4a75-a4c5-90178092a157</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
