<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Round Trip_0-departcity</name>
   <tag></tag>
   <elementGuidId>dc19228d-d418-4264-a1da-e070ccbc7092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='0-departcity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;0-departcity&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd1beae1-176f-454d-a31f-8e04f3131f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>259c7cae-36d5-4014-8112-ff9aeb593617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1w3ZZo _1YBGQV _2EjOJB lZd1T6 _2vegSu _2mFmU7</value>
      <webElementGuid>02d66337-d4b6-48af-919f-12ef56b5b1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scoopclassname</name>
      <type>Main</type>
      <value>_3pJKMX</value>
      <webElementGuid>aec4377f-5e1b-4be5-ac2f-a6215b03687f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>884dd601-039e-41de-8bf1-d41365c6b5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>0-departcity</value>
      <webElementGuid>4d28663a-b818-45fd-bdd6-d81f1a2b5c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>01</value>
      <webElementGuid>a01ac2cd-c1c2-40e2-bd6f-281444011627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_2I_P4n _6t1WkM _3HqJxg&quot;]/div[@class=&quot;_1AtVbE col-12-12&quot;]/div[@class=&quot;_3-tSyS _36bm8T&quot;]/div[@class=&quot;_3XCEEm&quot;]/div[@class=&quot;_1dTDqB&quot;]/div[@class=&quot;_2ffI1H&quot;]/form[@class=&quot;_1DLh40&quot;]/div[@class=&quot;_2NKqZI&quot;]/div[@class=&quot;_3REAgv&quot;]/div[@class=&quot;_1OSdiW&quot;]/div[@class=&quot;GTbXbG&quot;]/div[@class=&quot;_3qBKP_ _1Jqgld&quot;]/input[@class=&quot;_1w3ZZo _1YBGQV _2EjOJB lZd1T6 _2vegSu _2mFmU7&quot;]</value>
      <webElementGuid>d971484b-eab6-48f8-93f7-f6c6e096a48d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='0-departcity']</value>
      <webElementGuid>ef4550cb-42ac-4e95-97ff-eea02c77f142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[2]/div/div/div[2]/div/div[2]/form/div/div/div/div/div/input</value>
      <webElementGuid>b2d6e50c-a4ed-4d58-b93a-a897a496b79e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>4d14749c-d2af-4a1b-93e6-24b175f5b581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = '0-departcity']</value>
      <webElementGuid>de3c5132-3a98-412f-949d-6fcde2cc7279</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
