<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>f02ca8d2-4deb-4491-9257-ac1a684fd506</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Above 12 years'])[1]/following::*[name()='svg'][2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>bcd0b6ee-449c-49fc-aa3d-b35dc7e0eb3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>d6836751-c7b9-4e31-9e21-f57dce92b045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>1e94fc8b-4d51-4b68-b699-5252a31a4316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>44c4fef9-1d96-49e9-ad67-49478f53b48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 12 12</value>
      <webElementGuid>c9f98a51-b567-4a3b-b0ee-22dd4793113a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_2I_P4n _6t1WkM _3HqJxg&quot;]/div[@class=&quot;_1AtVbE col-12-12&quot;]/div[@class=&quot;_3-tSyS _36bm8T&quot;]/div[@class=&quot;_3XCEEm&quot;]/div[@class=&quot;_1dTDqB&quot;]/div[@class=&quot;_2ffI1H&quot;]/form[@class=&quot;_1DLh40&quot;]/div[@class=&quot;_2NKqZI&quot;]/div[@class=&quot;_3OFDG8&quot;]/div[@class=&quot;_1psGvi _19UjdT&quot;]/div[@class=&quot;ZEl_b_ _2pgFiz _2ogGYG _23xUYh _3pAV4E&quot;]/div[@class=&quot;_3_Fivj&quot;]/div[1]/div[@class=&quot;_3BV5Vj&quot;]/div[@class=&quot;_2i400y&quot;]/div[@class=&quot;_2g4weU _3mOkvM&quot;]/div[@class=&quot;_1Di8FC&quot;]/div[@class=&quot;_1_YMe_&quot;]/div[@class=&quot;_39P_Au _1A8Phq&quot;]/div[@class=&quot;VjWsXZ&quot;]/button[@class=&quot;_2KpZ6l _34K0qG _37Ieie&quot;]/svg[1]</value>
      <webElementGuid>c5f4009e-66ad-442f-9092-7223d45bf56c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Above 12 years'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>85b82040-e6c0-4844-ac29-9a405e292369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adults'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>320d6a6f-4d30-4ca0-845f-d2715e64133b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Children'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>14fbb575-cf52-4572-8345-df515d7a0e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Between 2-12 years'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>7a848769-a8e8-43a2-a3c8-48a062a09b7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
