<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Brand__24_Dny</name>
   <tag></tag>
   <elementGuidId>72a0b4f7-9a48-414c-8236-f7b8e5f32e51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._24_Dny</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div[2]/div/div/section[3]/div[2]/div/div[2]/div/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>81c62c4a-bb03-4787-923a-fb14f90e10d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_24_Dny</value>
      <webElementGuid>a09b9d3b-857a-4d6e-a5da-e9d6d0765e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_6t1WkM _3HqJxg&quot;]/div[@class=&quot;_1YokD2 _2GoDe3&quot;]/div[@class=&quot;_1AtVbE col-2-12&quot;]/div[@class=&quot;_1KOcBL&quot;]/section[@class=&quot;_167Mu3 _2hbLCH&quot;]/div[@class=&quot;_3FPh42&quot;]/div[@class=&quot;_2d0we9&quot;]/div[@class=&quot;_4921Z t0pPfW&quot;]/div[@class=&quot;_1Y4Vhm _4FO7b6&quot;]/label[@class=&quot;_2iDkf8 t0pPfW&quot;]/div[@class=&quot;_24_Dny&quot;]</value>
      <webElementGuid>e150d9a3-4f00-449b-a382-b91ba0420162</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div[2]/div/div/section[3]/div[2]/div/div[2]/div/label/div</value>
      <webElementGuid>385559cd-22f9-4eb6-b4d1-0723048436c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>3e0deded-2a8a-4768-879d-a7cc08fbbdd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
