<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Men</name>
   <tag></tag>
   <elementGuidId>85d0ac3e-599d-4fdb-b879-17af4b3f1932</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[2]/div/div/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span._2I9KP_._2WDRax</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b73e386f-2b11-4061-9e1e-77ec48f57b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2I9KP_ _2WDRax</value>
      <webElementGuid>e7daa6d8-fd86-4312-ace5-05d440dab5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Men</value>
      <webElementGuid>0db79807-e1d3-401c-b57f-72d84f592c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_331-kn&quot;]/div[@class=&quot;_3Il5oO dwRsDN&quot;]/div[@class=&quot;_1kidPb&quot;]/span[@class=&quot;_2I9KP_ _2WDRax&quot;]</value>
      <webElementGuid>187dfa3b-dde9-46d3-b865-6086f90dce5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[2]/div/div/span[3]</value>
      <webElementGuid>a8df333a-ea8c-4dda-a724-db109b0a5512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TVs &amp; Appliances'])[1]/following::span[1]</value>
      <webElementGuid>0d2aecb8-c1c1-495f-996b-2054e4859b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Electronics'])[1]/following::span[2]</value>
      <webElementGuid>a2041fbb-2e2d-48a4-b1f7-e14fc938b2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Women'])[1]/preceding::span[1]</value>
      <webElementGuid>b61d1e46-6fda-4a91-97fd-7f9180115480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baby &amp; Kids'])[1]/preceding::span[2]</value>
      <webElementGuid>1e030e03-ff94-40f1-abc8-e665e6c8fbb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Men']/parent::*</value>
      <webElementGuid>e79c417a-4b25-444e-8714-af6f69929b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>1e24c70f-423b-47b6-85f6-4a4b076d5426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Men' or . = 'Men')]</value>
      <webElementGuid>21166305-46b8-4605-90e0-7625c2f23a37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
