<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lightings</name>
   <tag></tag>
   <elementGuidId>6b5a9c9d-5daf-48d1-8f4d-83eff6695beb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[2]/div/div/div[6]/a/div[2]/div[2]/div[2]/div/div/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>57d36017-9e11-46bf-942b-c3bc0abe2fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6WOcW9 _3YpNQe</value>
      <webElementGuid>1b01d0ca-2712-4542-96d3-ea385b36ceef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.flipkart.com/home-lighting/decor-lighting-accessories/pr?sid=jhg,6w8&amp;otracker=categorytree&amp;fm=neo%2Fmerchandising&amp;iid=M_339c9531-c771-4012-957b-8bdf626d0219_1_372UD5BXDFYS_MC.NX0O0YGFEHU0&amp;otracker=hp_rich_navigation_2_1.navigationCard.RICH_NAVIGATION_Home~Home+Decor~Lightings_NX0O0YGFEHU0&amp;otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_2_L2_view-all&amp;cid=NX0O0YGFEHU0</value>
      <webElementGuid>f077d2cc-e830-4022-9666-0aa434c09f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lightings</value>
      <webElementGuid>22867bb9-9d90-4a80-b22a-babeba15fb4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_331-kn _2tvxW&quot;]/div[@class=&quot;InyRMC _3Il5oO&quot;]/div[@class=&quot;_37M3Pb&quot;]/div[@class=&quot;eFQ30H&quot;]/a[1]/div[@class=&quot;_1psGvi SLyWEo&quot;]/div[@class=&quot;ZEl_b_ _3joddx _2ogGYG _23xUYh _3pAV4E&quot;]/div[@class=&quot;_3_Fivj&quot;]/div[@class=&quot;_1y9fNR&quot;]/div[@class=&quot;_2IjXr8&quot;]/div[@class=&quot;_3XS_gI&quot;]/a[@class=&quot;_6WOcW9 _3YpNQe&quot;]</value>
      <webElementGuid>b3ebe31d-e452-46c3-b03c-e031733e4d12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[2]/div/div/div[6]/a/div[2]/div[2]/div[2]/div/div/div[2]/a[2]</value>
      <webElementGuid>d037fd4b-d0f9-4b99-b961-a0330968ebf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Lightings')])[2]</value>
      <webElementGuid>b3e755f1-247e-4907-963f-cebaec499428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::a[1]</value>
      <webElementGuid>96a9d229-155d-4c07-8df7-f4310e133015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='more in Home Decor'])[1]/following::a[2]</value>
      <webElementGuid>e7fb586e-4d60-4c0b-a708-037e7f14d5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stickers &amp; Wallpapers'])[1]/preceding::a[1]</value>
      <webElementGuid>987f94b8-7642-45a8-914a-e4b5c388efe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paintings &amp; Posters'])[1]/preceding::a[2]</value>
      <webElementGuid>4d6a58cb-6499-49f4-983e-2f85ec23ac47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lightings']/parent::*</value>
      <webElementGuid>9bde2caf-dc67-4a95-aa0b-8583579b3e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.flipkart.com/home-lighting/decor-lighting-accessories/pr?sid=jhg,6w8&amp;otracker=categorytree&amp;fm=neo%2Fmerchandising&amp;iid=M_339c9531-c771-4012-957b-8bdf626d0219_1_372UD5BXDFYS_MC.NX0O0YGFEHU0&amp;otracker=hp_rich_navigation_2_1.navigationCard.RICH_NAVIGATION_Home~Home+Decor~Lightings_NX0O0YGFEHU0&amp;otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_2_L2_view-all&amp;cid=NX0O0YGFEHU0')]</value>
      <webElementGuid>0536bf81-bc32-4ca8-b818-d8581cef96c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[2]</value>
      <webElementGuid>349bc15e-3e70-40cd-8b4b-aa173457b04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.flipkart.com/home-lighting/decor-lighting-accessories/pr?sid=jhg,6w8&amp;otracker=categorytree&amp;fm=neo%2Fmerchandising&amp;iid=M_339c9531-c771-4012-957b-8bdf626d0219_1_372UD5BXDFYS_MC.NX0O0YGFEHU0&amp;otracker=hp_rich_navigation_2_1.navigationCard.RICH_NAVIGATION_Home~Home+Decor~Lightings_NX0O0YGFEHU0&amp;otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_2_L2_view-all&amp;cid=NX0O0YGFEHU0' and (text() = 'Lightings' or . = 'Lightings')]</value>
      <webElementGuid>0ca7c31b-01df-4d8c-b8dc-97dc44fb2da2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
