<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mobiles</name>
   <tag></tag>
   <elementGuidId>54a235bb-b5cc-4a79-ba90-5bbb3dd8d60e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[2]/div/div/div[3]/a/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5a24719e-74f9-4af8-837d-1ba7c4109e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xtXmba</value>
      <webElementGuid>75e2e062-7871-4d51-9c59-ce28444fa420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mobiles</value>
      <webElementGuid>4f8b8644-8344-41c4-a8f6-a0620eec4321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_331-kn _2tvxW&quot;]/div[@class=&quot;InyRMC _3Il5oO&quot;]/div[@class=&quot;_37M3Pb&quot;]/div[@class=&quot;eFQ30H&quot;]/a[1]/div[@class=&quot;xtXmba&quot;]</value>
      <webElementGuid>9a596130-26f6-41b5-b6c1-d9d5f759fcd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[2]/div/div/div[3]/a/div[2]</value>
      <webElementGuid>81a55f6c-4223-429a-958c-17f1258951c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grocery'])[1]/following::div[4]</value>
      <webElementGuid>89113ab8-6f1a-4660-a9ca-a439c406a496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top Offers'])[1]/following::div[8]</value>
      <webElementGuid>425b83ce-3f3a-47a3-a5a9-18648f576bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fashion'])[1]/preceding::div[3]</value>
      <webElementGuid>086e6697-3ee4-43a2-b5a5-1bd2add9ed81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Electronics'])[1]/preceding::div[9]</value>
      <webElementGuid>7730fd31-5811-45dc-aab4-628e359cab44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mobiles']/parent::*</value>
      <webElementGuid>bf2399f0-09eb-4b2e-a347-69a2a8728a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/div[2]</value>
      <webElementGuid>48441d3b-1d52-4817-b339-a03d16cd04a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Mobiles' or . = 'Mobiles')]</value>
      <webElementGuid>d93ca010-a4b1-44d4-91f7-c8d2846163ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
