<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Price -- Low to High</name>
   <tag></tag>
   <elementGuidId>a7923570-4c2a-4b22-a27b-42cda84bbeea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div/div[2]/div/div/div/div[2]/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>719e343a-0fd2-4056-9ec7-4c46eb138a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_10UF8M</value>
      <webElementGuid>90e4c3a5-8cea-45c7-8b56-2b1fbc8bf3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Price -- Low to High</value>
      <webElementGuid>78cbff48-a93f-48d4-b9af-d2bb347a28f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_36fx1h _6t1WkM _3HqJxg&quot;]/div[@class=&quot;_1YokD2 _2GoDe3&quot;]/div[@class=&quot;_1YokD2 _3Mn1Gg&quot;]/div[@class=&quot;_1YokD2 _2GoDe3 col-12-12&quot;]/div[@class=&quot;_1AtVbE&quot;]/div[@class=&quot;W_R1IA&quot;]/div[@class=&quot;_5THWM1&quot;]/div[@class=&quot;_10UF8M&quot;]</value>
      <webElementGuid>6cc67c59-8e6d-4809-8e3a-e46584102e40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div[2]/div/div/div/div[2]/div[3]</value>
      <webElementGuid>f2b6844f-7ac2-424b-9887-530e910adc66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popularity'])[1]/following::div[1]</value>
      <webElementGuid>edc9e1db-7512-4cdf-bc68-4bc18115609c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relevance'])[1]/following::div[2]</value>
      <webElementGuid>5be9f8b9-5a75-4013-9e11-708e4f6d06ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price -- High to Low'])[1]/preceding::div[1]</value>
      <webElementGuid>0032b6d8-7e71-4d9c-ad32-87fd2e3472d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newest First'])[1]/preceding::div[2]</value>
      <webElementGuid>0a507c1f-2eea-4ec7-8606-24e2094c1bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Price -- Low to High']/parent::*</value>
      <webElementGuid>9b7dbe3d-d07c-42c1-a93c-48a9f72d41cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div[3]</value>
      <webElementGuid>c86806cd-e201-409a-ac30-a4723a9059c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Price -- Low to High' or . = 'Price -- Low to High')]</value>
      <webElementGuid>f81b94d4-2750-44bb-b627-68eb7a382c1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
