<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Free delivery__2r_T1I</name>
   <tag></tag>
   <elementGuidId>0075c150-6794-41c0-afbd-7b34a9bd3b84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div/div[2]/div[9]/div/div/div/a/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bcb992c2-a373-4f53-b7dd-d4a50781a1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2r_T1I</value>
      <webElementGuid>7306002d-2722-440d-9186-651292c06dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://rukminim1.flixcart.com/image/612/612/k7qinbk0/cases-covers/sleeve/p/z/u/glink-reversible-15-6-inch-laptop-sleeve-original-imafpwzxzjuhgyn5.jpeg?q=70</value>
      <webElementGuid>0e1505f5-9205-4219-88a6-bd37fe7d4549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_36fx1h _6t1WkM _3HqJxg&quot;]/div[@class=&quot;_1YokD2 _2GoDe3&quot;]/div[@class=&quot;_1YokD2 _3Mn1Gg&quot;]/div[@class=&quot;_1AtVbE col-12-12&quot;]/div[@class=&quot;_13oc-S&quot;]/div[1]/div[@class=&quot;_1xHGtK _373qXS e30oNt&quot;]/a[@class=&quot;_2UzuFa&quot;]/div[1]/div[1]/div[@class=&quot;_3ywSr_&quot;]/div[@class=&quot;_312yBx SFzpgZ&quot;]/img[@class=&quot;_2r_T1I&quot;]</value>
      <webElementGuid>878f8b3c-f728-483a-a8e9-605326644d33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div[2]/div[9]/div/div/div/a/div/div/div/div/img</value>
      <webElementGuid>8f70517a-e99f-4b59-b7de-414199f356ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://rukminim1.flixcart.com/image/612/612/k7qinbk0/cases-covers/sleeve/p/z/u/glink-reversible-15-6-inch-laptop-sleeve-original-imafpwzxzjuhgyn5.jpeg?q=70')]</value>
      <webElementGuid>ad4f1a6a-8960-4261-af50-516fd05c38a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/a/div/div/div/div/img</value>
      <webElementGuid>dc385c69-04a8-4ea7-978f-bd9584a34c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://rukminim1.flixcart.com/image/612/612/k7qinbk0/cases-covers/sleeve/p/z/u/glink-reversible-15-6-inch-laptop-sleeve-original-imafpwzxzjuhgyn5.jpeg?q=70']</value>
      <webElementGuid>3a915a09-c97e-459d-9ac1-d8f609d50471</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
